VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "tpDocumento"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public DataProcessamento As Long
Public IdLote As Long
Public IdEnvelope As Long
Public IdDocto As Long
Public Leitura As String
Public Frente As String
Public Verso As String
Public Status As String
Public Alcada As String
Public Duplicado As String
Public Autenticado As String
Public Ocorrencia As Long
Public OcorrenciaOK As String
Public Ordem As String
Public ValorTotal As Currency
Public NSU As String
Public Terminal As Integer
Public Vinculo As Long
Public CMC7Associado As String
Public Duplicidade As String
Public TipoDocto As Integer
Public Atualizacao As Long
Public Transacao As Integer
Public Efetivado As Boolean
Public PagtoTerceiro As String
Public TotalVinculado As Currency
Public Excluido As Boolean
Public AjusteInterno As Boolean
Public Agencia As Integer
Public Conta As Long
Public AgenciaVinculo As Integer
Public ContaVinculo As Long
Public Envelope As Long
