/*
    filename :  b32.h
    Synopsis:   
    Date:       October the 25th of 1993

COPYRIGHT (c) 1992 Matrox Electronic Systems Ltd.
All Rights Reserved
*/

#ifndef __B32_H__
#define __B32_H__

/* define operating system */
#ifndef BORLAND_32
#define BORLAND_32 1
#endif

#define MFAR
#define MHUGE
#define FTYPE
#define PTYPE
#define MFAR_1M
#define far
#define huge

/* define number of boards */
#define T_N_OF_BOARDS  4

#endif /* __B32_H__ */
