/*                                                                                                                                 
    filename :  msdos.h
    Synopsis:   Defines everything to compile magiclib for DOS
    Date:       15-09-92  MLO  created

COPYRIGHT (c) 1992 Matrox Electronic Systems Ltd.
All Rights Reserved.
*/

#ifndef __MSDOS_H__
#define __MSDOS_H__

/* define operating system */
#ifndef MA_MS_DOS
#define MA_MS_DOS
#endif

#define MFAR  far
#define MHUGE huge
#define FTYPE
#define PTYPE
#define MFAR_1M far 


/* define number of boards */
#define T_N_OF_BOARDS  4

#endif /* __MSDOS_H__ */
