/*
    filename :  watcom.h
    Synopsis:   
    Date:       October the 25th of 1993

COPYRIGHT (c) 1992 Matrox Electronic Systems Ltd.
All Rights Reserved
*/

#ifndef __WATCOM_H__
#define __WATCOM_H__

/* define operating system */
#ifndef WATCOM
#define WATCOM
#endif

#define MFAR  
#define MHUGE  
#define FTYPE  
#define PTYPE 
#define MFAR_1M far

/* define number of boards */
#define T_N_OF_BOARDS  4

#endif /* __WATCOM_H__ */



