/*                                                                                                                                /* 
    filename :  win310.h
    Synopsis:   
    Date:       July the 20th 1992

COPYRIGHT (c) 1992 Matrox Electronic Systems Ltd.
All Rights Reserved
*/

#ifndef __WIN310_H__
#define __WIN310_H__

/* define operating system */
#ifndef T_WINDOWS
#define T_WINDOWS
#endif

#define MFAR  far
#define MHUGE huge
#define FTYPE far pascal
#define PTYPE far
#define MFAR_1M far


/* define number of boards */
#define T_N_OF_BOARDS  4

#endif /* __WIN310_H__ */


