USE [VENDAS]
GO

/****** Object:  Table [dbo].[FONTE]    Script Date: 25/08/2020 20:53:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE [dbo].[FONTE]
GO
CREATE TABLE [dbo].[FONTE](
	[ID_FONTE] [int] NOT NULL,
	[DESC_FONTE] [nchar](50) NULL,
	[POTENCIA] [nchar](10) NULL,
	[CERTIF_80_PLUS] [nchar](3) NULL,
	[PFC_ATIVO] [nchar](3) NULL,
	[VALOR] [money] NULL,
	[FORNECEDOR] [nchar](20) NULL,
	[URL] [char](999) NULL,
 CONSTRAINT [PK_FONTE] PRIMARY KEY CLUSTERED 
(
	[ID_FONTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


