USE [VENDAS]
GO

/****** Object:  Table [dbo].[SOCKET]    Script Date: 25/08/2020 19:45:15 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SOCKET]') AND type in (N'U'))
DROP TABLE [dbo].[SOCKET]
GO

/****** Object:  Table [dbo].[SOCKET]    Script Date: 25/08/2020 19:45:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SOCKET](
	[ID_SOCKET] [int] NOT NULL,
	[DESC_SOCKET] [nchar](10) NOT NULL,
 CONSTRAINT [PK_SOCKET] PRIMARY KEY CLUSTERED 
(
	[ID_SOCKET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO [dbo].[SOCKET] ([ID_SOCKET] ,[DESC_SOCKET]) VALUES (6,'LGA 1200')
